module "zipper_lambda" {
  source = "./lambda"
  name   = "zipper"
  role = "${aws_iam_role.iam_for_lambda.arn}"
}

#resource "aws_lambda_function" "zipper_lambda" {
#  filename         = "zipper.zip"
#  function_name    = "zipper"
#  description      = "Generated by terraform"
#  role             = "${aws_iam_role.iam_for_lambda.arn}"
#  runtime          = "nodejs6.10"
#  handler          = "index.handler"
#  source_code_hash = "${base64sha256(file("zipper.zip"))}"
#
#  environment {
#    variables = {
#      foo = "bar"
#    }
#  }
#
#  # unfortunately tags are not supported
#  # tags {
#  #  terraform = true
#  #}
#}
