variable "name" {}
variable "role" {}

variable "environment" {
  type = "map"

  default = {
    comment = "Unfortunately, at least one field is expected inside environment"
  }
}

# The Function

resource "aws_lambda_function" "function" {
  filename         = "../build/${var.name}.zip"
  function_name    = "${var.name}"
  description      = "Generated by terraform"
  role             = "${var.role}"
  runtime          = "nodejs6.10"
  handler          = "index.handler"
  source_code_hash = "${base64sha256(file("../build/${var.name}.zip"))}"

  environment {
    variables = "${var.environment}"
  }
}

output "arn" {
  value = "${aws_lambda_function.function.arn}"
}
