
variable "name" {} # this is the input parameter of the module
#variable "region" {} # this is the input parameter of the module
#variable "accountId" {} # this is the input parameter of the module
#variable "rest_api_id" {}
variable "role" {}
#variable "root_id" {}

# The Function

resource "aws_lambda_function" "the_lambda" {
  filename         = "${var.name}.zip"
  function_name    = "${var.name}"
  description      = "Generated by terraform"
  role             = "${var.role}"
  runtime          = "nodejs6.10"
  handler          = "index.handler"
  source_code_hash = "${base64sha256(file("${var.name}.zip"))}"

  # unfortunately tags are not supported
  # tags {
  #  terraform = true
  #}
}

output "arn" {
  value = "${aws_lambda_function.the_lambda.arn}"
}
