variable "name" {}
variable "role" {}

# The Function

resource "aws_lambda_function" "function" {
  filename         = "../build/${var.name}.zip"
  function_name    = "${var.name}"
  description      = "Generated by terraform"
  role             = "${var.role}"
  runtime          = "python3.6"
  handler          = "lambda_function.lambda_handler"
  source_code_hash = "${base64sha256(file("../build/${var.name}.zip"))}"
}

output "arn" {
  value = "${aws_lambda_function.function.arn}"
}
